aaev2/aaev/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import patterns, url
from django.core.urlresolvers import reverse_lazy
from django.views.generic import RedirectView
from aaev import views

urlpatterns= patterns('',
    url(r'^$', views.index, name='index'),
    url(r'^registro/$', views.registro, name='registro'),
    url(r'^ingresar/$',views.login,name='ingresar'),
    url(r'^registro/completar/$', views.registrar, name='formularioRegistro'),
    url(r'^docente/$', views.inicioDocente, name='inicioDocente'),
    url(r'^salir/$', views.logout, name='cerrarSesion'),
    )

aaev2/aaev2/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'aaev2.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^aaev/', include('aaev.urls', namespace='aaev')),  #mis url de la app
    #declaro un namespace para evitar lio al llamar URLs

)

aaev2/aaev/models.py
# This is an auto-generated Django model module.
# You'll have to do the following manually to clean this up:
#   * Rearrange models' order
#   * Make sure each model has one field with primary_key=True
#   * Remove `managed = False` lines if you wish to allow Django to create, modify, and delete the table
# Feel free to rename the models, but don't rename db_table values or field names.
#
# Also note: You'll have to insert the output of 'django-admin.py sqlcustom [app_label]'
# into your database.
from __future__ import unicode_literals

from django.db import models


class Alumno(models.Model):
    idalumno = models.IntegerField(db_column='idAlumno')  # Field name made lowercase.
    nombre = models.CharField(max_length=45)
    apellido = models.CharField(max_length=45)
    mail = models.CharField(max_length=45)
    dni = models.TextField()
    idlogin = models.ForeignKey('Login', db_column='idLogin')  # Field name made lowercase.

    class Meta:
        managed = False
        db_table = 'alumno'


class AlumnoHasMateria(models.Model):
    idalumno = models.ForeignKey(Alumno, db_column='idAlumno', primary_key=True)  # Field name made lowercase.
    idmateria = models.ForeignKey('Materia', db_column='idMateria', primary_key=True)  # Field name made lowercase.
    habilitado = models.IntegerField()

    class Meta:
        managed = False
        db_table = 'alumno_has_materia'


class Carrera(models.Model):
    idcarrera = models.IntegerField(db_column='idCarrera', primary_key=True)  # Field name made lowercase.
    nombre = models.CharField(max_length=45)
    cantidadanios = models.IntegerField(db_column='cantidadAnios')  # Field name made lowercase.

    class Meta:
        managed = False
        db_table = 'carrera'

    def __str__(self):
        return self.nombre


class Docente(models.Model):
    iddocente = models.IntegerField(primary_key=True, db_column='idDocente')  # Field name made lowercase.
    nombre = models.CharField(max_length=45)
    apellido = models.CharField(max_length=45)
    mail = models.CharField(max_length=45)
    dni = models.TextField()
    idlogin = models.ForeignKey('Login', db_column='idLogin')  # Field name made lowercase.

    class Meta:
        managed = False
        db_table = 'docente'


class DocenteHasMateria(models.Model):
    iddocente = models.ForeignKey('Docente', db_column='idDocente', primary_key=True)  # Field name made lowercase.
    idmateria = models.ForeignKey('Materia', db_column='idMateria', primary_key=True)  # Field name made lowercase.

    class Meta:
        managed = False
        db_table = 'docente_has_materia'


class Examen(models.Model):
    idexamen = models.IntegerField(db_column='idExamen')  # Field name made lowercase.
    cantpreguntas = models.IntegerField(db_column='cantPreguntas')  # Field name made lowercase.
    totalpuntos = models.FloatField(db_column='totalPuntos')  # Field name made lowercase.
    descripcion = models.TextField(blank=True)
    duracion = models.TimeField()
    fechacierre = models.DateField(db_column='fechaCierre')  # Field name made lowercase.
    cerrado = models.IntegerField()
    visible = models.IntegerField()
    idmateria = models.ForeignKey('Materia', db_column='idMateria')  # Field name made lowercase.

    class Meta:
        managed = False
        db_table = 'examen'


class ExamenHasAlumno(models.Model):
    idexamen = models.ForeignKey(Examen, db_column='idExamen')  # Field name made lowercase.
    idalumno = models.ForeignKey(Alumno, db_column='idAlumno')  # Field name made lowercase.
    nota = models.FloatField()
    nrointentos = models.IntegerField(db_column='nroIntentos')  # Field name made lowercase.
    estado = models.CharField(max_length=45)

    class Meta:
        managed = False
        db_table = 'examen_has_alumno'


class Login(models.Model):
    idlogin = models.IntegerField(db_column='idLogin', primary_key=True)  # Field name made lowercase.
    usuario = models.CharField(max_length=45)
    clave = models.CharField(max_length=45)
    privilegio = models.IntegerField()
    activo = models.IntegerField()

    class Meta:
        managed = False
        db_table = 'login'
    def __str__(self):
        return self.usuario


class Materia(models.Model):
    idmateria = models.IntegerField(db_column='idMateria', primary_key=True)  # Field name made lowercase.
    nombre = models.CharField(max_length=45)
    aniocarrera = models.IntegerField(db_column='anioCarrera')  # Field name made lowercase.

    class Meta:
        managed = False
        db_table = 'materia'


class Opcion(models.Model):
    idopcion = models.IntegerField(db_column='idOpcion')  # Field name made lowercase.
    texto = models.CharField(max_length=45)
    correcta = models.IntegerField()
    imagen = models.BinaryField(blank=True)
    descripcionimagen = models.CharField(db_column='descripcionImagen', max_length=45, blank=True)  # Field name made lowercase.
    idopcion_correcta = models.ForeignKey('self', db_column='idOpcion_correcta', blank=True, null=True)  # Field name made lowercase.
    idpregunta = models.ForeignKey('Pregunta', db_column='idPregunta')  # Field name made lowercase.

    class Meta:
        managed = False
        db_table = 'opcion'


class Pregunta(models.Model):
    idpregunta = models.IntegerField(db_column='idPregunta')  # Field name made lowercase.
    texto = models.CharField(max_length=45)
    idtipopregunta = models.ForeignKey('Tipopregunta', db_column='idTipoPregunta')  # Field name made lowercase.
    idunidad = models.ForeignKey('Unidad', db_column='idUnidad')  # Field name made lowercase.

    class Meta:
        managed = False
        db_table = 'pregunta'


class SolicitudMateria(models.Model):
    idsolicitud_materia = models.IntegerField(db_column='idSolicitud_materia', primary_key=True)  # Field name made lowercase.
    materia_idmateria = models.ForeignKey(Materia, db_column='Materia_idMateria')  # Field name made lowercase.
    docente_iddocente = models.ForeignKey(Docente, db_column='Docente_idDocente')  # Field name made lowercase.
    fecha = models.DateField()

    class Meta:
        managed = False
        db_table = 'solicitud_materia'


class SolicitudRegistro(models.Model):
    idsolicitud_registro = models.IntegerField(db_column='idSolicitud_Registro', primary_key=True)  # Field name made lowercase.
    nombre = models.CharField(max_length=45)
    apellido = models.CharField(max_length=45)
    mail = models.CharField(max_length=45)
    dni = models.TextField(max_length=30)
    solicitud = models.TextField(blank=True)

    class Meta:
        managed = False
        db_table = 'solicitud_registro'


class Tipopregunta(models.Model):
    idtipopregunta = models.IntegerField(db_column='idTipoPregunta', primary_key=True)  # Field name made lowercase.
    nombretipo = models.CharField(db_column='nombreTipo', max_length=45)  # Field name made lowercase.

    class Meta:
        managed = False
        db_table = 'tipopregunta'


class Unidad(models.Model):
    idunidad = models.IntegerField(db_column='idUnidad', primary_key=True)  # Field name made lowercase.
    nombre = models.CharField(db_column='Nombre', max_length=45)  # Field name made lowercase.
    idmateria = models.ForeignKey(Materia, db_column='idMateria')  # Field name made lowercase.

    class Meta:
        managed = False
        db_table = 'unidad'


class UnidadHasExamen(models.Model):
    examen_idexamen = models.ForeignKey(Examen, db_column='Examen_idExamen')  # Field name made lowercase.
    unidad_idunidad = models.ForeignKey(Unidad, db_column='Unidad_idUnidad')  # Field name made lowercase.

    class Meta:
        managed = False
        db_table = 'unidad_has_examen'


class Universidad(models.Model):
    iduniversidad = models.IntegerField(db_column='idUniversidad', primary_key=True)  # Field name made lowercase.
    nombre = models.CharField(db_column='Nombre', max_length=45)  # Field name made lowercase.
    dominiomail = models.CharField(db_column='dominioMail', max_length=45)  # Field name made lowercase.
    class Meta:
        managed = False
        db_table = 'universidad'

    def __str__(self):
        return self.nombre


class UniversidadHasCarrera(models.Model):

    universidad_iduniversidad = models.ForeignKey(Universidad, db_column='Universidad_idUniversidad', primary_key=True )  # Field name made lowercase.
    carrera_idcarrera = models.ForeignKey(Carrera, db_column='Carrera_idCarrera', primary_key=True)  # Field name made lowercase.
    materia_idmateria = models.ForeignKey(Materia, db_column='Materia_idMateria', primary_key=True)  # Field name made lowercase.
#Django necesita que las tablas tengan una PK definida, para esto se agrega primery_key=True, sino falla
    class Meta:
        managed = False
        db_table = 'universidad_has_carrera'
    def __str__(self):
        return self.carrera_idcarrera

"""
La consulta en las tablas intermedias es la siguiente
Quiero obtener las carreras de una universidad
carreras_qs = UniversidadHasCarrera.objecs.filter(universidad_iduniversidad=1)
------
osea que primero agarro el queryset de la universidad
luego filtro por el objeto implicito que esta adentro del modelo, si es igual al
queryset saca las carreras que tiene esa uni. Luego se hace:
----
carreras= Carrera.objects.filter(universidadhascarrera=carreras_qs)
"""

aaev2/aaev/views.py
# -*- coding: utf-8 -*-
from django.shortcuts import render
from aaev.models import Login, Universidad, UniversidadHasCarrera
from aaev.models import Carrera, Alumno, SolicitudRegistro, Login
from aaev.models import Docente, DocenteHasMateria,Materia
from django.shortcuts import redirect
from django.views.decorators.csrf import ensure_csrf_cookie

from django import forms
from django.shortcuts import render_to_response
from django.http import HttpResponseRedirect
from django.contrib.auth.forms import UserCreationForm
from django.core.context_processors import csrf
from django.core.urlresolvers import reverse_lazy
from django.forms import ModelForm
from django.http import Http404
from funciones import validarLogin, traerCantInscriptosMateria
from funciones import traerCantSolicitantesMateria
from funciones import traerCantUnidadesMateria, traerCantExamenesMateria
from funciones import traerCantPreguntasUnidad, traerCantPreguntasMateria
from django.views.decorators.csrf import csrf_protect

from django.template.defaulttags import register


# ----------------------------------- VISTAS -------------------------
@csrf_protect
def index(request):
    return render(request, 'index.html', None)

@csrf_protect
def login(request):
        if request.method == 'POST':
            form = LoginForm(request.POST) #agarro el formulario de ingreso
            if form.is_valid():
                nombre = form.cleaned_data['usuario']
                clave = form.cleaned_data['clave']
                if validarLogin(nombre,clave):
                    usuario = Login.objects.get(usuario=nombre)
                    request.session['usuario'] = str(usuario.usuario)
                    if usuario.privilegio == 2:
                        mensaje="Sesion iniciada"
                        docente = Docente.objects.get(idlogin = usuario.idlogin)
                        request.session['docente'] = str(docente.iddocente)
                        context = {'mensaje': mensaje,
                                   'docente': docente}
                        return redirect('aaev:inicioDocente')
                        pass
                    else:
                        pass
                else:
                        mensaje="Usuario y/o clave incorrectos"
                        context = {'mensaje': mensaje}
                        return render(request, 'index.html', context)
            else:
              return render_to_response('index.html', {'form': form})
        else:
            form = UserCreationForm()
            token = {}
            token.update(csrf(request))
            token['form'] = form

            return render_to_response('index.html', token)

def inicioDocente(request):
    try:
        if request.session['usuario']:
            nombreUsuario = request.session['usuario']
            usuario = Login.objects.get(usuario=nombreUsuario)
            docente = Docente.objects.get(idlogin = usuario.idlogin)
            try:
                materias = DocenteHasMateria.objects.filter(iddocente=docente.iddocente)
                materias = Materia.objects.filter(docentehasmateria=materias) #materias del docente
            except (DocenteHasMateria.DoesNotExist, Materia.DoesNotExist):
                materias=None #si no existen agrego None
            context = {'usuario': usuario, 'docente': docente, 'materias': materias}
            return render(request,'inicioDocente.html', context)
        else:
            return redirect('aaev:index')
    except:
        return redirect('aaev:index')

def logout(request):
    if request.method == 'POST':
        del request.session['usuario']
        return redirect('aaev:index')


@ensure_csrf_cookie
def registro(request):
    lista_universidades= Universidad.objects.all()
     #traigo las carreras de la universidad

    context= {  }
    return render(request, 'Registro.html', context)


def registrar(request):
    if request.method == 'POST':
         form = UserCreationForm(request.POST)
         if form.is_valid():
             if form.privilegio==1:
                 alumno = Alumno(form.nombre, form.apellido, form.dni, form.email, form.clave, form.clave2)

                 return HttpResponseRedirect(reverse_lazy('aaev:formularioRegistro'))
             else:
                 solicitudDocente = SolicitudRegistro(form.nombre, form.apellido, form.dni, form.emailDocente, form.mensaje)
                 solicitudDocente.save()
                 return HttpResponseRedirect(reverse_lazy('aaev:formularioRegistro'))
    else:
         form = UserCreationForm()
         token = {}
         token.update(csrf(request))
         token['form'] = form

         return render_to_response('Registro_completo.html', token)


##-------------------------FORM DE MODELOS PARA ABM--------------------
class LoginForm(ModelForm):
    class Meta:
        model = Login
        fields = ['usuario', 'clave']




"""
 context= {'universidades': lista_universidades,
        'carreras': None,
        'materias': None,
             }
    #context={'carreras': carreras_lista}
    if request.method == 'POST':
        return ajaxRegistroCarreras(request,universidad.iduniversidad)


@ensure_csrf_cookie
def ajaxRegistroCarreras(request,id):
    universidad = Universidad.objects.get(pk=id) #traigo las carreras de la universidad
    carreras_queryset = UniversidadHasCarrera.objects.filter(universidad_iduniversidad=universidad.iduniversidad)
    carreras_lista = Carrera.objects.filter(universidadhascarrera=carreras_queryset)
    #context={'carreras': carreras_lista}
    print(carreras_lista)
    num= 1
    context={
    'carreras': carreras_lista,
    'num': num,
    }
    html = render_to_string('ajaxRegistroCarreras.html',context)
    return render(request,'ajaxRegistroCarreras.html',context)
    #return HttpResponse(html, content_type="application/json")

class RegistrarSolicitudForm(ModelForm):
    class Meta:
         model = SolicitudRegistro
         fields = ['nombre','apellido','dni','email']

        """
#------------------------METODOS PARA TEMPLATES--------------------
@register.filter
def contarPreguntas(materia):
    return traerCantPreguntasMateria(materia)

@register.filter
def contarUnidades(materia):
    return traerCantUnidadesMateria(materia)

@register.filter
def contarInscriptos(materia):
    return traerCantInscriptosMateria(materia)

@register.filter
def contarSolicitantes(materia):
    return traerCantSolicitantesMateria(materia)

@register.filter
def contarExamenes(materia):
    return traerCantExamenesMateria(materia)

@register.filter
def vacio(numero):
    if numero==0:
        return True
    else:
        return False

aaev2/aaev/templates/AjaxRegistroCarreras.html
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
{% load staticfiles %}
<script src="{% static 'aaev/material.min.js' %}"></script>
<script src="{% static 'aaev/getmdl-select.min.js' %}"></script>
<script src="{% static 'aaev/jquery.js' %}"></script>
<link rel="stylesheet" href="{% static 'aaev/getmdl-select.min.css' %}"/>
<link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons"></link>
<link rel="stylesheet" href="https://code.getmdl.io/1.2.0/material.red-blue.min.css"></link>
<meta name="viewport" content="width=device-width, initial-scale=1.0"></meta> <!-- dispositivos moviles -->
<script type="text/javascript">

$(document).ready(function(){
		$("#carreraOpcion").click(function(){
				var idCarreraSeleccionada= $("#carreraOpcion").val();
				$("#idCarrera").val(idCarreraSeleccionada);
				
		});

});
</script>

	
	
	
	<div class="mdl-cell--12-col mdl-textfield mdl-js-textfield mdl-textfield--floating-label
										getmdl-select getmdl-select__fullwidth">
										  <!-- Simple Select -->
											
												<input class="mdl-textfield__input" type="text" id="elegirCarrera" value="Elegir" readonly tabIndex="-1">
												<label for="elegirCarrera" class="mdl-textfield__label">Seleccione carrera</label>
												<ul id="menuUniversidad" for="elegirCarrera" class="mdl-menu mdl-menu--bottom-left mdl-js-menu">
												{% for carrera in carreras %}
												<li id="carreraOpcion"
												class="mdl-menu__item" value="{{carrera.idcarrera}}"> {{carrera.nombre}} </li>
												<!-- 
													<li class="mdl-menu__item" value="1">(UNLa) Universidad Nacional de Lanus</li>
													<li class="mdl-menu__item">(UNLZ) Universidad Nacional de Lomas de Zamora</li>
													<li class="mdl-menu__item">(UBA) Universidad de Buenos Aires</li>
												-->
												</ul>
												{% endfor %}
		<input type="button" id="mostrarCarreras" value="VER"/>
	</div><!--Universidades-->

aaev2/aaev/templates/Registro_completo.html
<html>
<head>
<title> Registro completo </title>

</head>
<body>

</body>
</html>

aaev2/aaev/templates/index.html
<html>
<head>

<title> AAEV 2.0: Ingreso </title>
{% load staticfiles %}
<script src="{% static 'aaev/material.min.js' %}"></script>
<script src=" {% static 'aaev/jquery.js' %}"></script>
<script src=" {% static 'aaev/DjangoAjax.js' %}"></script>

<link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
<link rel="stylesheet" href="https://code.getmdl.io/1.2.1/material.green-light_green.min.css" />


</head>
<script type="text/javascript">
	$(document).ready(function(){
		$("#login").click(function(){
			
			var usuario= $("#usuario").val();
			var clave = $("#clave").val();
			if(usuario == null || clave == null){
				$("#mensajeError").display='inline';
				$("#mensajeError").html("Por favor completa todos los campos");
			}
		});
	});

</script>

<body>

<!-- Square card -->
<style>
.mdl-layout {
  align-items: center;
  justify-content: center;
}
.demo-card-square.mdl-card {
  width: 420px;
  height: 320px;
}
 
.demo-card-square > .mdl-card__title {
  color: #ffffff;
  background: #6666cc;
}
   
</style>
<!--titulo AAEV 2.0-->
<div class="mdl-layout mdl-js-layout mdl-layout--fixed-header">
	<header class="mdl-layout__header">
		<div class= "mdl-layout__header-row">
			<span class="mdl-layout-title" style="color: white;"> AAEV 2.0 </span>
			<div class="mdl-layout-spacer"></div>
		</div>
	</header>
	<main class="mdl-layout__content">
		<div class="page-content">
			<div class="mdl-grid">
				<div class="demo-card-square mdl-card mdl-shadow--8dp" style="margin-top: 8%; align: center;">
					<div class="mdl-card__title mdl-card--expand">
						<h2 class="mdl-card__title-text">Ingreso</h2>
					</div>
				  <div class="mdl-card__supporting-text">
					<form action=" {% url 'aaev:ingresar' %}" method="POST">
					{% csrf_token %}
					  <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
						<input class="mdl-textfield__input" type="text" id="usuario" name="usuario">
						<label class="mdl-textfield__label" for="usuario">Usuario</label>
					  </div>
					  <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
						<input class="mdl-textfield__input" type="password" id="clave" name="clave">
						<label class="mdl-textfield__label" for="clave">Clave</label>
					  </div>
					  {% if mensaje %}
						<h5 style="color: red;"> {{mensaje}} </h5>
						<h5> {{nombre}} </h5>
					  {% endif %}
					  {% if form.errors %}
						
						<div>
							<strong style="color: red;">ASEGURATE DE COMPLETAR TODOS LOS CAMPOS</strong>
						</div>
					
				{% endif %}
				  </div>
					
					  <div class="mdl-card__actions mdl-card--border">
						<input type="submit" name="login" id="login" value="Ingresar"
						class="mdl-button mdl-button--colored mdl-js-button mdl-js-ripple-effect">
						<!--<div class="mdl-layout-spacer"></div> -->	
					</form>
						<a class="mdl-button mdl-button--colored mdl-js-button mdl-js-ripple-effect" href="{% url 'aaev:registro' %}">Registrarse</a>
						
					  </div>

				</div>
			</div>
			<div id="mensajeError" style="display: none;">
			</div>
		</div>
	</main>
</div>


</body>
</html>

aaev2/aaev/templates/inicioDocente.html
<html>
<head>
<title> Docente: {{docente.nombre}} {{docente.apellido}}</title>
{% load staticfiles %}
<script src="{% static 'aaev/material.min.js' %}"></script>
<script src=" {% static 'aaev/jquery.js' %}"></script>
<script src=" {% static 'aaev/DjangoAjax.js' %}"></script>

<link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
<link rel="stylesheet" href="https://code.getmdl.io/1.2.1/material.green-light_green.min.css" />


</head>
<style>
.demo-card-wide.mdl-card {
  width: 800px;
}

.demo-card-wide > .mdl-card__title {

  align-items: center;
  justify-content: center;
  color: #ffffff;
  background: #6666cc;
}

.demo-card-wide > .mdl-card__supporting-text {

  align-items: center;
  justify-content: center;

}
#boton{

	height: 50px;
}

button {
     background:none!important;
     border:none; 
     padding:0!important;
     font: inherit;
     /*border is optional*/
     border-bottom:1px solid #444; 
     cursor: pointer;
}


</style>
<script language="JavaScript" type="text/javascript">

	function submit(){
				
				document.getElementById("form").submit();
			
	}
</script>
<body>
	{% if docente %}
	<div class="mdl-layout mdl-js-layout mdl-layout--fixed-header">
		<header class="mdl-layout__header">
			<div class="mdl-layout__header-row  mdl-shadow--8dp">
				<span class="mdl-layout-title" style="color: white;"> AAEV 2.0 / Docente {{docente.nombre}} {{docente.apellido}}</span>
				<div class="mdl-layout-spacer"></div>
				<nav class="mdl-navigation">
				<form method="POST" action="{% url 'aaev:cerrarSesion'%}" name="form"  id="form">
				{% csrf_token %}
					<a id="boton" style="color: white;" class="mdl-navigation__link" onclick="document.getElementById('form'),submit();" href="#">Cerrar sesion</a>
				</form>
				</nav>
			</div>
		</header>
		<main class="mdl-layout__content" id="cuerpo">
			<div class="page-content content-grid mdl-grid">
				<div style="margin-top: 6%;">
					<div class="demo-card-wide mdl-card mdl-shadow--8dp mdl-cell">
							<div  class="mdl-card__title mdl-card--expand"> 
								<h5 class="mdl-card__title-text"> Mis materias </h5>
							</div>
							<div class="mdl-card__supporting-text">
								<div>
									<p> Aca podes ver tus materias, examenes y demas.
								</div>
								<div>
									{% if materias %}
									<table class="mdl-data-table mdl-js-data-table">
										<thead>
											<tr>
												<th class="mdl-data-table-cel--non-numeric"> Materia </th>
												<th> Unidades </th>
												<th> Preguntas </th>
												<th> Examenes </th>
												<th> Alumnos pendientes </th>
												<th> Alumnos aceptados </th>
											</tr>
										<thead>
										<tbody>
											
											{% for materia in materias %}
											<tr onclick="console.log('click'); return false;">
											
												<td class="mdl-data-table-cel--non-numeric">{{materia.nombre}}</td>
												<td> {{ materia| contarUnidades }}	</td>
												<td> {{ materia| contarPreguntas }}</td>
												<td> {{ materia| contarExamenes}}	</td>
												{% if materia|contarSolicitantes|vacio %}
												<td style="color: #1bc700;"> Sin solicitudes </td>
												{% else %}
												<td style="color: #0fd7ff;"> {{ materia|contarSolicitantes}} </td>
												{% endif %}
												{% if materia|contarInscriptos|vacio %}
												<td style="color: #1bc700;"> Sin inscriptos </td>
												{% else %}
												<td style="color: #0fd7ff;"> {{ materia|contarInscriptos}} </td>
												{% endif %}
												
											</tr>
											{% endfor %}
										</tbody>
									</table>
									{% else %}
										<p> No tenes materias en este momento </p>
									{% endif %}
								
								</div>
							</div>
					</div>
					<div class="demo-card-wide mdl-card mdl-shadow--8dp mdl-cell">
						<div class="mdl-card__title mdl-card--expand">
							<h5 class="mdl-card__title-text"> Solicitud de Materia </h5>
						</div>
						<div class="mdl-card__supporting-text">
							<p>Escribi el mensaje para enviar al administrador indicando Universdiad, Carrera y materia que dictas</p>
							<div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
								<textarea class="mdl-textfield__input" name="mensajeSolicitud" rows="3"></textarea>
								<label for="mensajeSolicitud" class="mdl-textfield__label"> Escribi el mensaje aca </label>
							</div>
						</div>
						<div class="mdl-card__actions mdl-card--border">
						
						</div>
					
					</div>
				</div>
				
			</div>
		</main>
	</div>
	{% endif %}
</body>
</html>