preparando tercer hito/aaev2/aaev/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import patterns, url
from django.core.urlresolvers import reverse_lazy
from django.views.generic import RedirectView
from aaev import views



urlpatterns= patterns('',
    url(r'^$', views.index, name='index'),
    url(r'^registro/$', views.registro, name='registro'),
    url(r'^ingresar/$',views.login,name='ingresar'),
    url(r'^registro/registrarAlumno/$', views.registrar, name='registrarAlumno'),
    url(r'^registro/enviarDatos/$', views.envioSolicitudRegistroDocente, name='registrarDocente'),
    url(r'^docente/$', views.inicioDocente, name='inicioDocente'),
    url(r'^docente/(?P<iduniversidad>\d+)/$', views.traerCarrerasId ,name='traerCarrerasId'),
    url(r'^docente/(?P<iduniversidad>\d+)/(?P<idcarrera>\d+)/$', views.traerMateriasId, name='traerMateriasId'),
    url(r'^docente/enviarSolicitud/$', views.enviarSolicitudMateria, name='enviarSolicitudMateria'),
    url(r'^salir/$', views.logout, name='cerrarSesion'),
    #url(r'^docente/(?P<iduniversidad>\d+)/$', views.traerCarrerasId, name='traerCarrerasId'),
    )

preparando tercer hito/aaev2/aaev2/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'aaev2.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^aaev/', include('aaev.urls', namespace='aaev')),  #mis url de la app
    #declaro un namespace para evitar lio al llamar URLs

)

preparando tercer hito/aaev2/aaev/views.py
# -*- coding: utf-8 -*-
#--------------------METODOS DJANGO --------------------
from django.shortcuts import render #cargar html con contexto
from django.shortcuts import redirect #redireccionar a una url 
from django.views.decorators.csrf import ensure_csrf_cookie #asegurar cookie
from django.http import HttpResponse #envia texto en respuesta
from django import forms #formularios genericos
from django.shortcuts import render_to_response #render de una respuesta
from django.http import HttpResponseRedirect
from django.core.context_processors import csrf #uso de tokens
from django.core.urlresolvers import reverse_lazy #redireccionamiento  (creo que no usado)
from django.forms import ModelForm # formulario basado en modelos
from django.http import Http404 # error 404
from django.views.decorators.csrf import csrf_protect #proteger el csrf
from django.template.defaulttags import register #para uso de metodos en templates
import json #LENGUAJE JSON
from django.template.loader import render_to_string #plantillas a string
from django.template import Template, Context #generacion de plantillas
import datetime #fechas
from django.contrib import messages #mensajes al redirigir la pagina, usado como session, solo que se eliminan al recargar
#--------------------MODELOS ------------------------------
from aaev.models import Login, Universidad, UniversidadHasCarrera
from aaev.models import Carrera, Alumno, SolicitudRegistro, Login
from aaev.models import Docente, DocenteHasMateria, Materia, SolicitudMateria
#--------------------FUNCIONES PROPIAS--------------------
from funciones import validarLogin, traerCantInscriptosMateria, traerDocente
from funciones import traerCantSolicitantesMateria
from funciones import traerCantUnidadesMateria, traerCantExamenesMateria
from funciones import traerCantPreguntasUnidad, traerCantPreguntasMateria
from funciones import verificarMateriasSolicitadas, verificarMateriasObtenidas

# -----------------------------------CONTROLADORES DE VISTAS -------------------------
@csrf_protect
def index(request):
    return render(request, 'index.html', None) #pagina de inicio, sin variables


def envioSolicitudRegistroDocente(request): #el docente completa el formulario de la pagina de registro
    if request.method == 'POST':
        form = solicitudRegistroForm(request.POST)
        if form.is_valid(): #si el campo es valido agarro los datos
            nombre = form.cleaned_data['nombre']
            apellido = form.cleaned_data['apellido']
            dni = str(form.cleaned_data['dni']) #aca lo hago texto para la base de datos, que usa VARCHAR
            email = form.cleaned_data['mail']
            solicitudMensaje = form.cleaned_data['solicitud']
            idsolicitud = 0
            try:
                solicitud = SolicitudRegistro.objects.latest('idsolicitud_registro')
                idsolicitud = solicitud.idsolicitud_registro + 1
            except(SolicitudRegistro.DoesNotExist):
                idsolicitud = 1

            try:
                solicitudDniExistente = SolicitudRegistro.objects.get(dni = dni)
                if solicitudDniExistente:
                    messages.add_message(request, messages.INFO, "Ya hay una solicitud o docente registrado con ese DNI")
                    return redirect('aaev:registro')
            except (SolicitudRegistro.DoesNotExist):
                if solicitud: #si se envio mensaje
                    solicitudGuardar = SolicitudRegistro(idsolicitud, nombre, apellido, email, dni, solicitudMensaje)
                else: #si no se envio
                    solicitudGuardar = SolicitudRegistro(idsolicitud, nombre, apellido, email, dni, ' ')
                solicitudGuardar.save()
                messages.add_message(request, messages.INFO, "Solicitud de registro enviada! Tu solicitud se ha enviado al administrador para ser evaluada")
                return redirect('aaev:registro')
        else:
            messages.add_message(request, messages.INFO, "Asegurate de completar todos los campos")
            return redirect('aaev:registro')

    else:
        return redirect('aaev:registro')

def login(request): #inicio de sesion de los usuarios
        if request:
            if request.method == 'POST':
                form = LoginForm(request.POST) #agarro el formulario de ingreso
                if form.is_valid():
                    nombre = form.cleaned_data['usuario']
                    clave = form.cleaned_data['clave']
                    if validarLogin(nombre,clave):
                        usuario = Login.objects.get(usuario=nombre)
                        request.session['usuario'] = str(usuario.usuario)
                        if usuario.privilegio == 2:
                            mensaje="Sesion iniciada"
                            docente = Docente.objects.get(idlogin = usuario.idlogin)
                            request.session['docente'] = str(docente.iddocente)
                            context = {'mensaje': mensaje,
                                       'docente': docente}
                            return redirect('aaev:inicioDocente')
                            pass
                        else:
                            pass
                    else:
                            mensaje="Usuario y/o clave incorrectos"
                            context = {'mensaje': mensaje}
                            return render(request, 'index.html', context)
                else:
                    mensaje="Completa todos los campos"
                    context = {'mensaje': mensaje}
                    return render(request, 'index.html', context)
                    #return redirect('aaev:index')
            else:
                return redirect('aaev:index')
        else:
            redirect('aaev:index')

def inicioDocente(request):
    try:
        if request.session['usuario']:
            nombreUsuario = request.session['usuario']
            usuario = Login.objects.get(usuario=nombreUsuario)
            docente = Docente.objects.get(idlogin = usuario.idlogin)
            mensaje = ''
            try:
                mensaje = request.session['mensajeExito'] #si vengo de una solicitud agarro el mensaje
                del request.session['mensajeExito'] #borro la entrada de diccionario
            except (KeyError): # si no hay mensaje
                mensaje = None
            try:
                materias = DocenteHasMateria.objects.filter(iddocente=docente.iddocente)
                materias = Materia.objects.filter(docentehasmateria=materias) #materias del docente
                universidades = Universidad.objects.all() 
            except (DocenteHasMateria.DoesNotExist, Materia.DoesNotExist):
                materias=None #si no existen agrego None
            context = {'usuario': usuario, 'docente': docente, 'materias': materias, 'universidades': universidades,
            'mensaje': mensaje}
            return render(request,'inicioDocente.html', context)
        else:
            return redirect('aaev:index')
    except ('usuario' not in request.session):
        return redirect('aaev:index')


def logout(request):
    try:#si estoy logeado
        usuario = request.session['usuario']
        usuario = Usuario.objects.get(usuario=usuario)
        privilegio = usuario.privilegio
        if request.method == 'POST': #si es un post
            del request.session['usuario']
            if privilegio == 2:# si soy docente
                del request.session['docente']
            return redirect('aaev:index')
        else: #si entre por URL
            if privilegio == 2: #si soy docente llevo a su inicio
                return redirect('aaev:inicioDocente')  
    except:
        return redirect('aaev:index')


@ensure_csrf_cookie
def registro(request):
    lista_universidades= Universidad.objects.all()
     #traigo las carreras de la universidad

    context= {  }
    return render(request, 'Registro.html', context)


def registrar(request):
    if request.method == 'POST':
         form = UserCreationForm(request.POST)
         if form.is_valid():
             if form.privilegio==1:
                 alumno = Alumno(form.nombre, form.apellido, form.dni, form.email, form.clave, form.clave2)

                 return HttpResponseRedirect(reverse_lazy('aaev:formularioRegistro'))
             else:
                 solicitudDocente = SolicitudRegistro(form.nombre, form.apellido, form.dni, form.emailDocente, form.mensaje)
                 solicitudDocente.save()
                 return HttpResponseRedirect(reverse_lazy('aaev:formularioRegistro'))
    else:
        return redirect('aaev:registro')

def traerCarrerasId(request, iduniversidad):
    if request.method == 'POST':
        iddocente=  int(request.session['docente'])
        docente = Docente.objects.get(pk=iddocente)
        idBusqueda=iduniversidad #agarro el id de la universidad que envio ajax
        uhc= UniversidadHasCarrera.objects.filter(universidad_iduniversidad=idBusqueda)
        if uhc:
            carreras = Carrera.objects.filter(universidadhascarrera=uhc) #consultas
            data = {'carreras': carreras, 'iduniversidad': idBusqueda}
            
            #return HttpResponse(json.dumps(data), content_type='application/json') #envio el html guardado como cadena de texto
            return render(request, "AjaxCarreras.html", data)
        else:
            mensaje= "No hay carreras disponibles en esta universidad"
            data = {'mensaje': mensaje}
            return render(request, "AjaxCarreras.html", data)
    else:
        error= "Error al ejecutar el request"
        return HttpResponse(json.dumps(error), content_type='application/json') #envio el html guardado como cadena de texto;

def traerMateriasId(request, iduniversidad, idcarrera): #aca se hace la validacion final de inscripcion
    if request.is_ajax() and request.method=='POST': # si es ajax y post

preparando tercer hito/aaev2/aaev/templates/AjaxMaterias.html
<html>
<head>
{% load staticfiles %}

<script src="{% static 'aaev/DjangoAjax.js' %}"></script>
<script src="{% static 'aaev/getmdl-select.min.js' %}"></script>
<script src=" {% static 'aaev/jquery.js' %}"></script>
<script src="{% static 'aaev/material.min.js' %}"></script>
<link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
<link rel="stylesheet" href="https://code.getmdl.io/1.2.1/material.green-light_green.min.css" />
</head>
<script>

$(document).ready(function(){

	$("#menuMateria").on('change', function(){
		var id = $("#menuMateria :selected").val();
		console.log(id);

	});

	$("#submitSolicitud").click(function(event){
		event.preventDefault();
		var iduniversidad = $("#iduniversidad").val();
		var idcarrera = $("#idcarrera").val();
		var idmateria = $("#materia_idmateria :selected").val();
		var url =iduniversidad  + "/" + idcarrera + "/" + idmateria + "/"; 
		if (idmateria==0){
			var html = "<h4> Por favor elegi una materia. </h4>";
			$("#errorForm").html(html);
		} else{
			//$.post(url, {idmateria: idmateria, mensaje: mensaje});
			$("#formularioEnvio").submit();
		}
	//jquery validator: buscar
	});

});

</script>
<style>
.error{
	color: red;
	font-size: 12px;
}	

</style>
<body>

	{% if mensaje %}
	<div class="mdl-cell"> 
		<h4 class="error"> {{mensaje}} </h4>
	</div>
	{% endif %}
	{% if materias %}
	<form id="formularioEnvio" action= "{% url 'aaev:enviarSolicitudMateria' %}" method="POST"> 
	{% csrf_token %}
		<div class="mdl-selectfield mdl-js-selectfield mdl-selectfield--floating-label mdl-cell is-dirty is-upgraded">
			<select id="materia_idmateria" name="materia_idmateria" class="mdl-selectfield__select">
			  	<option   value="0" disabled="disabled" selected="selected"> Elegir...</option> 
			    {% for materia in materias %}
			    	<option   value="{{materia.idmateria}}"> {{materia.nombre}} </option>
			    {% endfor %}
			</select>
			
			<label class="mdl-selectfield__label" for="menuMateria">Seleccione materia</label>
			<span class="mdl-selectfield__error">Elegi materia</span>
		</div>
		<div class="mdl-card__supporting-text mdl-cell--10-col">
			<p>Escribi un mensaje/comentario (opcional)</p>
			<div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label" >
				<label for="mensajeSolicitud" class="mdl-textfield__label"> Escribi el mensaje aca </label>
				<textarea class="mdl-textfield__input"  id="mensaje" name="mensaje" rows="3" ></textarea>
			</div>
		</div>

		<div class="error" style="display: none;" id="errorForm">


		</div>
		<div class="mdl-card__actions mdl-card--border  mdl-cell--12-col">
			<div>
				<input type="submit" value="Enviar solicitud" id="submitSolicitud"
				class="mdl-button mdl-js-button mdl-button--raised mdl-shadow--8dp mdl-cell mdl-cell--12-col" id="registrarse">
				</input>
			</div>
		</div>

	</form>				
		<input type="hidden" value={{iduniversidad}} id="iduniversidad">
		<input type="hidden" value={{idcarrera}} id="idcarrera">
							
	</div>
	{% endif %}
</body>
</html>

preparando tercer hito/aaev2/aaev/templates/Registro.html
<html>
<head>

<title> Registro </title>
{% load staticfiles %}
<script src="{% static 'aaev/material.min.js' %}"></script>
<script src="{% static 'aaev/getmdl-select.min.js' %}"></script>
<script src="{% static 'aaev/jquery.js' %}"></script>
<script src="{% static 'aaev/DjangoAjax.js' %}"></script>
<script src="{% static 'aaev/jquery.validate.min.js' %}"></script>
<script src="{% static 'aaev/validaciones/registroDocenteValidar.js' %}"> </script>
<link rel="stylesheet" href="{% static 'aaev/getmdl-select.min.css' %}"/>
<link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons"></link>
<link rel="stylesheet" href="https://code.getmdl.io/1.2.1/material.green-light_green.min.css" />
<meta name="viewport" content="width=device-width, initial-scale=1.0"> <!-- dispositivos moviles -->
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
</head>
<style>

label.error{

	color: red;
}


.demo-card-wide.mdl-card {
  width: 512px;
  text-align: center;
}

.demo-card-wide > .mdl-card__title {

  text-align: -webkit-center;
  color: #ffffff;
  background: #6666cc;
}








</style>

<script type="text/javascript">
		
		function mostrarAlumno(){
			var alumno=document.getElementById("Alumno");
			var docente=document.getElementById("Docente");
			document.getElementById("Alumno").style.display='inline';
			document.getElementById("Docente").style.display='none';
		}
		
		function mostrarDocente(){
			
			var alumno= document.getElementById("Alumno");
			var docente= document.getElementById("Docente");
			document.getElementById("Alumno").style.display='none';
			document.getElementById("Docente").style.display='inline';
		
		}
		
			
	
		$(document).ready(function(){
			if (typeof jQuery != 'undefined') {  
	    // jQuery is loaded => print the version
		    console.log(jQuery.fn.jquery);

		    	if ($.validator) {
		    		// $.validator is defined
					console.log("cargado sistema de validaciones");
				}
			}


			$("#registrarse").click(function(event){
				event.preventDefault();
				var privilegio = $('input[name=privilegio]:checked').val();
				var nombre = $("#nombre").val();
				if( privilegio == 1){
					console.log(1);
				} else {
					console.log(2);
					console.log(nombre);
					$("#registrarDocente").validate();
					$("#registrarDocente").submit();
				}

			});
		});
	
	
	
	

</script>

<body>
	
	<div class="mdl-layout mdl-js-layout mdl-layout--fixed-header">
		<header class="mdl-layout__header">
			<div class="mdl-layout__header-row  mdl-shadow--8dp">
				<span class="mdl-layout-title" style="color: white;"> AAEV 2.0 </span>
				<div class="mdl-layout-spacer"></div>
				<nav class="mdl-navigation">
					<a class="mdl-navigation__link" style="color: white;" href=" {% url 'aaev:index' %}">Inicio</a>
				</nav>
			</div>
		</header>
		<main class="mdl-layout__content" id="cuerpo">
			<div class="page-content">
				<div class="mdl-grid mdl-cell--6-col" style="align-items: center; justify-content:center;"> 
					<div  style="margin-top: 50px;">
						<div class="demo-card-wide mdl-card mdl-shadow--8dp">
							<div  class="mdl-card__title mdl-card--expand"> 
								<h2 class="mdl-card__title-text"> REGISTRO </h2>
							</div>
							<div class="mdl-card__supporting-text">
								{% if messages %}
									{% for message in messages%}
										<h4 style="color: red; font-size: 14px;"> {{message}} </h4>
									{% endfor %}
								{% endif %}
								{% csrf_token %}
									<div >
										<label class="mdl-radio mdl-js-radio mdl-js-ripple-effect"
										for="opcionAlumno">
											<input class="mdl-radio__button" id="opcionAlumno" 
											type="radio" name="privilegio" onclick="mostrarAlumno()" value="1"checked/>
											<label class="mdl-radio__label" for="privilegioAlumno">Soy alumno</label>
										</label>
										<label class="mdl-radio mdl-js-radio mdl-js-ripple-effect"
										for="opcionDocente">
											<input class="mdl-radio__button" id="opcionDocente" 
											type="radio" name="privilegio" onclick="mostrarDocente()"  value="2" />
											<label class="mdl-radio__label" for="privilegioDocente">Soy docente</label>
										</label>
									</div>
									<!-- REGISTRO ALUMNO -->
									<div id="Alumno"> <!-- formulario de registro del alumno -->
										<form action="{% url 'aaev:registrarAlumno' %}" method="POST" id="registrarAlumno" name="registrarAlumno">
											<div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label 
											mdl-cell--12-col">
												<input class="mdl-textfield__input" type="text" id="nombre" name="nombre"/>
												<label class="mdl-textfield__label" for="nombre"> Ingresa tu nombre </label>
											</div>
											<div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label 
											mdl-cell--12-col">
												<input class="mdl-textfield__input" type="text" id="apellido" name="apellido"/>
												<label class="mdl-textfield__label" for="apellido"> Ingresa tu apellido </label>
											</div>
											<div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label 
											mdl-cell--12-col">
												<input class="mdl-textfield__input" type="text" id="dni" name="dni" />
												<label class="mdl-textfield__label" for="dni"> DNI </label>
											</div>
											<div class="mdl-cell--12-col mdl-textfield mdl-js-textfield 
											mdl-textfield--floating-label">
												<input class="mdl-textfield__input" type="email" id="email" name="email">
												<label for="email" class="mdl-textfield__label">E-mail</label>
												
											</div>
											<div class="mdl-cell--12-col mdl-textfield mdl-js-textfield 
											mdl-textfield--floating-label">
												<input class="mdl-textfield__input" id="clave"type="password" name="clave">
												<label for="clave" class="mdl-textfield__label">Clave</label>
											</div>
											<div class="mdl-cell--12-col mdl-textfield mdl-js-textfield 
											mdl-textfield--floating-label">
												<input class="mdl-textfield__input" id="clave2" type="password" name="clave2">
												<label for="clave2" class="mdl-textfield__label">Confirmar clave</label>
											</div>

										</form>
									</div> <!--div de alumno-->
									<div id="Docente" style="display: none;">
										<form method="POST" action="{% url 'aaev:registrarDocente' %}" id="registrarDocente" name="registrarDocente">
										{% csrf_token %}
											<div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label 
											mdl-cell--12-col">
												<input class="mdl-textfield__input" type="text" id="nombre" name="nombre"/>
												<label class="mdl-textfield__label" for="nombre"> Ingresa tu nombre </label>
											</div>
											<div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label 
											mdl-cell--12-col">
												<input class="mdl-textfield__input" type="text" id="apellido" name="apellido"/>
												<label class="mdl-textfield__label" for="apellido"> Ingresa tu apellido </label>
											</div>
											<div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label 
											mdl-cell--12-col">
												<input class="mdl-textfield__input" type="text" id="dni" name="dni" />
												<label class="mdl-textfield__label" for="dni"> DNI </label>
											</div>
											<div class="mdl-cell--12-col mdl-textfield mdl-js-textfield 
												mdl-textfield--floating-label">
													<input class="mdl-textfield__input" type="text" id="emailDocente" name="mail">
													<label for="email" class="mdl-textfield__label">E-mail (solo dominio academico)</label>
											</div>
											<div class="mdl-cell--12-col mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
												
											   <textarea class="mdl-textfield__input" type="text" rows= "3" id="text7" id="solicitud" name="solicitud"></textarea>
											   <label class="mdl-textfield__label" for="text7">Escribi un mensaje indicando Universidad, carrera y materia</label>
												
											</div>
										</form>
									</div><!-- div docente-->
									</div> <!-- supporting text -->
										<div class="mdl-card__actions mdl-card--border">
											<div>
												<input type="button" value="Registrarse"
												class="mdl-button mdl-js-button mdl-button--raised" id="registrarse">
												</input>
											</div>
										</div>
									{% if mensajeError%}
										<div class="mdl-grid mdl-cell--8-col" >
											<h4 style="color: red;"> {{mensaje}} </h4>
										</div>
									{%endif%}
									
								</form><!-- formularioRegistro-->
						</div> <!--carta-->
					
					</div><!--celda de grid-->
			    </div><!--grid-->
				<div id="prueba">
				
				</div>
			<input type="hidden" id="idUniversidad" name="idUniversidad" value=""/>
			</div> <!--contenido de la pagina-->
		</main>
	</div>
</body>
</html>

preparando tercer hito/aaev2/aaev/templates/Registro_completo.html
<html>
<head>
<title> Registro completo </title>

</head>
<body>

</body>
</html>

preparando tercer hito/aaev2/aaev/templates/index.html
<html>
<head>

<title> AAEV 2.0: Ingreso </title>
{% load staticfiles %}
<script src="{% static 'aaev/material.min.js' %}"></script>
<script src=" {% static 'aaev/jquery.js' %}"></script>
<script src=" {% static 'aaev/DjangoAjax.js' %}"></script>
<script src=" {% static 'aaev/jquery.validate.min.js' %}"></script>
<script src=" {% static 'aaev/validaciones/inicioSesionValidar.js' %}"></script>

<link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
<link rel="stylesheet" href="https://code.getmdl.io/1.2.1/material.green-light_green.min.css" />

<meta charset="UTF-8"/>
</head>
<script type="text/javascript">


</script>

<body>

<!-- Square card -->
<style>

label.error{
	color: red;
}

.mdl-layout {
  align-items: center;
  justify-content: center;
}
.demo-card-square.mdl-card {
  width: 420px;
  height: 320px;
}
 
.demo-card-square > .mdl-card__title {
  color: #ffffff;
  background: #6666cc;
}
   
</style>
<!--titulo AAEV 2.0-->
<div class="mdl-layout mdl-js-layout mdl-layout--fixed-header">
	<header class="mdl-layout__header">
		<div class= "mdl-layout__header-row">
			<span class="mdl-layout-title" style="color: white;"> AAEV 2.0 </span>
			<div class="mdl-layout-spacer"></div>
		</div>
	</header>
	<main class="mdl-layout__content">
		<div class="page-content">
			<div class="mdl-grid">
				<div class="demo-card-square mdl-card mdl-shadow--8dp  mdl-cell--12-col-desktop mdl-cell--4-col-phone" style="margin-top: 8%; align: center;">
					<div class="mdl-card__title mdl-card--expand">
						<h2 class="mdl-card__title-text">Ingreso</h2>
					</div>
				  <div class="mdl-card__supporting-text mdl-cell--4-col-phone">
					<form action=" {% url 'aaev:ingresar' %}" method="POST" name="iniciarSesion" id="iniciarSesion">
					{% csrf_token %}
					  <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
						<input class="mdl-textfield__input" type="text" id="usuario" name="usuario">
						<label class="mdl-textfield__label" for="usuario">Usuario</label>
					  </div>
					  <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
						<input class="mdl-textfield__input" type="password" id="clave" name="clave">
						<label class="mdl-textfield__label" for="clave">Clave</label>
					  </div>
					  {% if mensaje %}
						<h5 style="color: red;"> {{mensaje}} </h5>
						<h5> {{nombre}} </h5>
					  {% endif %}
					  {% if form.errors %}
						
						<div>
							<strong style="color: red;">ASEGURATE DE COMPLETAR TODOS LOS CAMPOS</strong>
						</div>
					
				{% endif %}
				  </div>
					
					  <div class="mdl-card__actions mdl-card--border mdl- cell mdl-cell--4-col-phone">
						<input type="submit" name="login" id="login" value="Ingresar"
						class="mdl-button mdl-button--colored mdl-js-button mdl-js-ripple-effect">
						<!--<div class="mdl-layout-spacer"></div> -->	
					</form>
						<a class="mdl-button mdl-button--colored mdl-js-button mdl-js-ripple-effect" href="{% url 'aaev:registro' %}">Registrarse</a>
						
					  </div>

				</div>
			</div>
			<div id="mensajeError" style="display: none;">
			</div>
		</div>
	</main>
</div>


</body>
</html>